export const COLLEGE_LIST = [
  "M. Kumarasamy College of Engineering",
  "VSB Engineering College",
  "Chettinad College of Engineering and Technology",
  "N.S.N. College of Engineering and Technology",
  "Arulmurugan College of Engineering",
  "Cheran College of Engineering",
  "VKS College of Engineering and Technology",
  "Karur College of Engineering",
  "Valluvar College of Science And Management",
  "Sasurie College of Engineering",
  "Jai Shriram Engineering College",
  "Builders Engineering College",
  "Angel College of Engineering and Technology",
  "Jairupaa College of Engineering",
  "Sri Ramanathan Engineering College",
  "Cheran College of Technology",
  "Ambal Professional Group of Institutions",
  "SCAD Institute of Technology",
  "Dr. Nallini Institute of Engineering and Technology",
  "KIT - Kangeyam Institute of Technology",
  "Professional Educational Trusts Group of Institutions Faculty of Engineering",
  "VSB College of Engineering Technical Campus",
  "Other",
] as const;
